-- 052 (consultation): more frequent
-- diagnoses - the list goes from 100 to about 300.
--
-- Decided by the director on 2026-10-02: the whole ICD-10 (about 12,000 codes) is not
-- loaded - the terms of use of the three languages' official lists do not fit a public
-- repository. "Let us pick the ones we are likely to need." So: the diagnoses seen in the
-- clinic's departments (general and family medicine, internal medicine, paediatrics,
-- gynaecology-obstetrics, surgery, orthopaedics, dermatology, emergency), what is common
-- in Madagascar, and the eye / ear-nose-throat / dental, mental-health and check-up codes
-- a general consultation meets.
--   - Codes are WHO ICD-10, three or four characters (edition 2010 and later). The code
--     column stays free text (050): the Ministry is moving its hospital reports to ICD-11.
--   - Names are OUR OWN short wording in the three languages, with the words used on site
--     in French - not the official titles. They have not been reviewed by the medical
--     staff; Settings -> Diagnostics corrects them.
--
-- A database already in use is not disturbed: a row is added only when NO row - active or
-- not - carries its code already. The rows that are there keep their names, their order
-- and their state. The new rows are placed after the last one. Running this twice adds
-- nothing the second time.
INSERT INTO diagnosis_code (code, name_en, name_fr, name_ko, sort_order)
SELECT v.code, v.name_en, v.name_fr, v.name_ko, base.last + v.n
  FROM (SELECT COALESCE(MAX(sort_order), 0) AS last FROM diagnosis_code) AS base,
       (VALUES
    ('A00.9', 'Cholera', 'Choléra', '콜레라', 10),
    ('A03.9', 'Bacillary dysentery (shigellosis)', 'Dysenterie bacillaire (shigellose)', '세균성 이질', 20),
    ('A07.1', 'Giardiasis', 'Giardiase (lambliase)', '람블편모충증', 30),
    ('A08.4', 'Viral gastroenteritis', 'Gastro-entérite virale', '바이러스 장염', 40),
    ('A15.0', 'Pulmonary tuberculosis, sputum positive', 'Tuberculose pulmonaire à crachats positifs (TB)', '폐결핵(가래 양성)', 50),
    ('A18.2', 'Tuberculous lymph nodes', 'Adénite tuberculeuse (ganglions)', '결핵성 림프절염', 60),
    ('A20.0', 'Bubonic plague', 'Peste bubonique', '림프절 페스트', 70),
    ('A20.2', 'Pneumonic plague', 'Peste pulmonaire', '폐 페스트', 80),
    ('A30.9', 'Leprosy', 'Lèpre', '한센병', 90),
    ('A35', 'Tetanus', 'Tétanos', '파상풍', 100),
    ('A37.9', 'Whooping cough', 'Coqueluche', '백일해', 110),
    ('A41.9', 'Sepsis', 'Septicémie (sepsis)', '패혈증', 120),
    ('A46', 'Erysipelas', 'Érysipèle', '단독', 130),
    ('B02.9', 'Shingles (zoster)', 'Zona', '대상포진', 140),
    ('B20', 'HIV disease with infections', 'Maladie à VIH avec infections', 'HIV 병(감염 합병)', 150),
    ('Z21', 'HIV positive, no symptoms', 'Séropositivité VIH sans symptôme', '무증상 HIV 감염', 160),
    ('B26.9', 'Mumps', 'Oreillons', '유행성 이하선염', 170),
    ('B37.0', 'Oral thrush', 'Muguet (candidose buccale)', '구강 칸디다증(아구창)', 180),
    ('B50.0', 'Severe falciparum malaria with cerebral signs', 'Paludisme grave (neuropaludisme)', '뇌 말라리아(중증)', 190),
    ('B65.0', 'Urinary schistosomiasis', 'Bilharziose urinaire', '방광 주혈흡충증', 200),
    ('B65.1', 'Intestinal schistosomiasis', 'Bilharziose intestinale', '장 주혈흡충증', 210),
    ('B76.9', 'Hookworm infection', 'Ankylostomiase', '구충증', 220),
    ('B80', 'Pinworm infection', 'Oxyurose', '요충증', 230),
    ('I11.9', 'Hypertensive heart disease', 'Cardiopathie hypertensive', '고혈압성 심장병', 240),
    ('I20.9', 'Angina', 'Angine de poitrine (angor)', '협심증', 250),
    ('I21.9', 'Acute myocardial infarction', 'Infarctus du myocarde aigu', '급성 심근경색', 260),
    ('I48', 'Atrial fibrillation or flutter', 'Fibrillation ou flutter auriculaire (FA)', '심방세동·조동', 270),
    ('I00', 'Rheumatic fever without heart involvement', 'Rhumatisme articulaire aigu (RAA) sans atteinte cardiaque', '류마티스열(심장 침범 없음)', 280),
    ('I63.9', 'Cerebral infarction', 'AVC ischémique (infarctus cérébral)', '뇌경색', 290),
    ('I61.9', 'Brain haemorrhage', 'AVC hémorragique (hémorragie cérébrale)', '뇌출혈', 300),
    ('I83.9', 'Varicose veins of the legs', 'Varices des membres inférieurs', '하지 정맥류', 310),
    ('J22', 'Acute lower respiratory infection', 'Infection respiratoire basse aiguë (IRA basse)', '급성 하기도감염', 320),
    ('J46', 'Severe acute asthma', 'Asthme aigu grave', '천식 지속상태(중증 급성 천식)', 330),
    ('E03.9', 'Hypothyroidism', 'Hypothyroïdie', '갑상선기능저하증', 340),
    ('E05.9', 'Hyperthyroidism', 'Hyperthyroïdie', '갑상선기능항진증', 350),
    ('E66.9', 'Obesity', 'Obésité', '비만', 360),
    ('E86', 'Dehydration', 'Déshydratation', '탈수', 370),
    ('M10.9', 'Gout', 'Goutte', '통풍', 380),
    ('D57.1', 'Sickle-cell disease', 'Drépanocytose', '겸상적혈구병', 390),
    ('K25.9', 'Gastric ulcer', 'Ulcère de l''estomac', '위궤양', 400),
    ('K58.9', 'Irritable bowel syndrome', 'Syndrome de l''intestin irritable (colopathie fonctionnelle)', '과민성 장증후군', 410),
    ('K74.6', 'Cirrhosis of the liver', 'Cirrhose du foie', '간경변', 420),
    ('K92.2', 'Gastrointestinal bleeding', 'Hémorragie digestive', '위장관 출혈', 430),
    ('N04.9', 'Nephrotic syndrome', 'Syndrome néphrotique', '신증후군', 440),
    ('N18.9', 'Chronic kidney disease', 'Insuffisance rénale chronique (IRC)', '만성 신장병', 450),
    ('G03.9', 'Meningitis', 'Méningite', '수막염', 460),
    ('G51.0', 'Facial palsy (Bell)', 'Paralysie faciale (a frigore)', '안면신경 마비(벨 마비)', 470),
    ('R04.0', 'Nosebleed', 'Épistaxis (saignement de nez)', '코피', 480),
    ('R06.0', 'Shortness of breath', 'Dyspnée (essoufflement)', '호흡곤란', 490),
    ('R07.4', 'Chest pain', 'Douleur thoracique', '흉통', 500),
    ('R10.1', 'Upper abdominal pain', 'Douleur épigastrique', '상복부 통증', 510),
    ('R17', 'Jaundice', 'Ictère (jaunisse)', '황달', 520),
    ('R21', 'Skin rash', 'Éruption cutanée', '발진', 530),
    ('R30.0', 'Painful urination', 'Dysurie (brûlures en urinant)', '배뇨통', 540),
    ('R31', 'Blood in the urine', 'Hématurie', '혈뇨', 550),
    ('R42', 'Dizziness', 'Vertiges, étourdissements', '어지럼', 560),
    ('R53', 'Tiredness', 'Fatigue (asthénie)', '피로·무력감', 570),
    ('R55', 'Fainting', 'Syncope, malaise', '실신', 580),
    ('R60.9', 'Oedema', 'Œdème', '부종', 590),
    ('R63.4', 'Weight loss', 'Amaigrissement', '체중 감소', 600),
    ('A08.0', 'Rotavirus gastroenteritis', 'Gastro-entérite à rotavirus', '로타바이러스 장염', 610),
    ('B08.4', 'Hand, foot and mouth disease', 'Syndrome pieds-mains-bouche', '수족구병', 620),
    ('E40', 'Kwashiorkor', 'Kwashiorkor', '콰시오커', 630),
    ('E41', 'Marasmus', 'Marasme', '마라스무스', 640),
    ('E43', 'Severe acute malnutrition', 'Malnutrition aiguë sévère (MAS)', '중증 영양실조', 650),
    ('E44.0', 'Moderate malnutrition', 'Malnutrition aiguë modérée (MAM)', '중등도 영양실조', 660),
    ('E55.0', 'Rickets', 'Rachitisme', '구루병', 670),
    ('J05.0', 'Croup', 'Laryngite aiguë obstructive (croup)', '크루프', 680),
    ('L22', 'Nappy rash', 'Érythème fessier du nourrisson', '기저귀 피부염', 690),
    ('P07.3', 'Preterm infant', 'Prématurité', '미숙아', 700),
    ('P36.9', 'Neonatal sepsis', 'Infection néonatale (sepsis du nouveau-né)', '신생아 패혈증', 710),
    ('P38', 'Umbilical infection of the newborn', 'Omphalite du nouveau-né', '신생아 배꼽염', 720),
    ('R56.0', 'Febrile convulsion', 'Convulsion fébrile', '열성 경련', 730),
    ('R56.8', 'Convulsion', 'Convulsion', '경련', 740),
    ('R62.8', 'Poor growth (failure to thrive)', 'Retard de croissance', '성장 부진', 750),
    ('Z00.1', 'Routine child health check', 'Examen de routine de l''enfant', '영유아 건강검진', 760),
    ('D24', 'Benign breast lump (fibroadenoma)', 'Tumeur bénigne du sein (adénofibrome)', '유방 양성 종양(섬유선종)', 770),
    ('C50.9', 'Breast cancer', 'Cancer du sein', '유방암', 780),
    ('C53.9', 'Cancer of the cervix', 'Cancer du col de l''utérus', '자궁경부암', 790),
    ('N70.9', 'Infection of the tubes and ovaries', 'Salpingite, annexite', '난관염·난소염', 800),
    ('N75.1', 'Bartholin abscess', 'Abcès de la glande de Bartholin (bartholinite)', '바르톨린샘 농양', 810),
    ('N83.2', 'Ovarian cyst', 'Kyste de l''ovaire', '난소 낭종', 820),
    ('N91.2', 'Absent periods', 'Aménorrhée', '무월경', 830),
    ('N92.0', 'Heavy periods', 'Règles abondantes (ménorragie)', '월경과다', 840),
    ('N93.9', 'Abnormal uterine bleeding', 'Saignement utérin anormal (métrorragie)', '비정상 자궁출혈', 850),
    ('N95.1', 'Menopause symptoms', 'Troubles de la ménopause', '폐경기 증상', 860),
    ('O00.9', 'Ectopic pregnancy', 'Grossesse extra-utérine (GEU)', '자궁외 임신', 870),
    ('O20.0', 'Threatened miscarriage', 'Menace d''avortement', '절박유산', 880),
    ('O13', 'High blood pressure of pregnancy', 'Hypertension gravidique', '임신성 고혈압', 890),
    ('O23.4', 'Urinary infection in pregnancy', 'Infection urinaire pendant la grossesse', '임신 중 요로감염', 900),
    ('O24.4', 'Gestational diabetes', 'Diabète gestationnel', '임신성 당뇨병', 910),
    ('O72.1', 'Postpartum haemorrhage', 'Hémorragie du post-partum', '분만 후 출혈', 920),
    ('O80.0', 'Normal vaginal delivery', 'Accouchement normal par voie basse', '자연 두위 분만', 930),
    ('O85', 'Puerperal infection', 'Infection puerpérale', '산욕열(산욕 패혈증)', 940),
    ('O91.2', 'Mastitis while breastfeeding', 'Mastite de l''allaitement', '수유기 유방염', 950),
    ('O98.6', 'Malaria in pregnancy', 'Paludisme pendant la grossesse', '임신 중 말라리아', 960),
    ('O99.0', 'Anaemia in pregnancy', 'Anémie pendant la grossesse', '임신 중 빈혈', 970),
    ('Z34.0', 'Antenatal care, first pregnancy', 'Consultation prénatale (CPN), première grossesse', '초임부 산전 관리', 980),
    ('Z39.2', 'Routine postnatal check', 'Consultation postnatale', '산후 진찰', 990),
    ('Z30.0', 'Family planning advice', 'Conseil en planification familiale', '피임 상담', 1000),
    ('Z12.4', 'Cervical cancer screening', 'Dépistage du cancer du col', '자궁경부암 선별검사', 1010),
    ('E04.9', 'Goitre', 'Goitre', '갑상선종', 1020),
    ('K35.8', 'Acute appendicitis', 'Appendicite aiguë', '급성 충수염', 1030),
    ('K40.3', 'Strangulated inguinal hernia', 'Hernie inguinale étranglée', '감돈 서혜부 탈장', 1040),
    ('K43.9', 'Ventral or incisional hernia', 'Hernie ventrale ou éventration', '복벽 탈장', 1050),
    ('K56.6', 'Bowel obstruction', 'Occlusion intestinale', '장폐색', 1060),
    ('K60.2', 'Anal fissure', 'Fissure anale', '치열', 1070),
    ('K61.0', 'Anal abscess', 'Abcès anal', '항문 농양', 1080),
    ('K62.5', 'Bleeding from the anus or rectum', 'Rectorragie', '항문·직장 출혈', 1090),
    ('K65.0', 'Acute peritonitis', 'Péritonite aiguë', '급성 복막염', 1100),
    ('K81.0', 'Acute cholecystitis', 'Cholécystite aiguë', '급성 담낭염', 1110),
    ('R10.0', 'Acute abdomen', 'Abdomen aigu', '급성 복증', 1120),
    ('L05.9', 'Pilonidal cyst', 'Kyste pilonidal', '모소낭', 1130),
    ('L60.0', 'Ingrowing nail', 'Ongle incarné', '내향성 손발톱', 1140),
    ('T81.4', 'Infection of a surgical wound', 'Infection de plaie opératoire', '수술 부위 감염', 1150),
    ('Z48.0', 'Dressing change or suture removal', 'Pansement, ablation de fils', '드레싱·봉합사 제거', 1160),
    ('N20.1', 'Stone in the ureter', 'Calcul de l''uretère', '요관 결석', 1170),
    ('N23', 'Renal colic', 'Colique néphrétique', '신산통', 1180),
    ('N34.1', 'Non-specific urethritis', 'Urétrite non spécifique', '비특이성 요도염', 1190),
    ('N44', 'Torsion of the testis', 'Torsion du testicule', '고환 염전', 1200),
    ('N45.9', 'Orchitis or epididymitis', 'Orchite, épididymite', '고환염·부고환염', 1210),
    ('N47', 'Phimosis', 'Phimosis', '포경', 1220),
    ('Q53.9', 'Undescended testis', 'Testicule non descendu (cryptorchidie)', '잠복고환', 1230),
    ('R33', 'Retention of urine', 'Rétention d''urine', '요 정체', 1240),
    ('M06.9', 'Rheumatoid arthritis', 'Polyarthrite rhumatoïde', '류마티스 관절염', 1250),
    ('M13.9', 'Arthritis', 'Arthrite', '관절염', 1260),
    ('M17.9', 'Osteoarthritis of the knee', 'Arthrose du genou (gonarthrose)', '무릎관절증', 1270),
    ('M51.1', 'Slipped disc with nerve pain', 'Hernie discale avec radiculalgie', '신경뿌리병증을 동반한 추간판 장애', 1280),
    ('M54.2', 'Neck pain', 'Cervicalgie', '경부통', 1290),
    ('M54.3', 'Sciatica', 'Sciatique', '좌골신경통', 1300),
    ('M75.0', 'Frozen shoulder', 'Capsulite rétractile de l''épaule', '오십견(유착성 관절낭염)', 1310),
    ('M79.1', 'Muscle pain', 'Myalgie', '근육통', 1320),
    ('M81.9', 'Osteoporosis', 'Ostéoporose', '골다공증', 1330),
    ('M86.9', 'Osteomyelitis', 'Ostéomyélite', '골수염', 1340),
    ('G56.0', 'Carpal tunnel syndrome', 'Syndrome du canal carpien', '손목터널 증후군', 1350),
    ('S42.0', 'Fracture of the clavicle', 'Fracture de la clavicule', '쇄골 골절', 1360),
    ('S42.4', 'Fracture of the lower end of the humerus', 'Fracture de l''extrémité inférieure de l''humérus (supracondylienne)', '상완골 원위부 골절', 1370),
    ('S52.4', 'Fracture of both forearm bones', 'Fracture des deux os de l''avant-bras', '요골·척골 몸통 골절', 1380),
    ('S52.5', 'Fracture of the wrist (lower end of radius)', 'Fracture du poignet (extrémité inférieure du radius)', '요골 원위부 골절', 1390),
    ('S62.6', 'Fracture of a finger (not the thumb)', 'Fracture d''un doigt (hors pouce)', '손가락 골절(엄지 제외)', 1400),
    ('S72.0', 'Fracture of the neck of the femur', 'Fracture du col du fémur', '대퇴골 경부 골절', 1410),
    ('S72.3', 'Fracture of the shaft of the femur', 'Fracture de la diaphyse du fémur', '대퇴골 몸통 골절', 1420),
    ('S82.2', 'Fracture of the shaft of the tibia', 'Fracture de la diaphyse du tibia', '경골 몸통 골절', 1430),
    ('S82.6', 'Fracture of the ankle (lateral malleolus)', 'Fracture de la malléole externe', '외측 복사 골절', 1440),
    ('S43.0', 'Dislocated shoulder', 'Luxation de l''épaule', '어깨 탈구', 1450),
    ('S53.0', 'Pulled elbow (radial head)', 'Pronation douloureuse (luxation de la tête radiale)', '요골두 탈구(팔꿈치 빠짐)', 1460),
    ('S83.6', 'Knee sprain', 'Entorse du genou', '무릎 염좌', 1470),
    ('S93.4', 'Ankle sprain', 'Entorse de la cheville', '발목 염좌', 1480),
    ('B07', 'Warts', 'Verrues', '사마귀', 1490),
    ('B35.0', 'Ringworm of the scalp', 'Teigne du cuir chevelu', '두부 백선', 1500),
    ('B35.1', 'Fungal nail infection', 'Onychomycose', '손발톱 백선', 1510),
    ('B35.3', 'Athlete''s foot', 'Pied d''athlète (intertrigo des orteils)', '발 백선(무좀)', 1520),
    ('B36.0', 'Pityriasis versicolor', 'Pityriasis versicolor', '어루러기', 1530),
    ('B85.0', 'Head lice', 'Poux de tête (pédiculose)', '머릿니', 1540),
    ('B88.1', 'Jigger flea infestation (tungiasis)', 'Tungose (puce-chique, parasy)', '모래벼룩증', 1550),
    ('L02.4', 'Abscess or boil of a limb', 'Abcès ou furoncle d''un membre', '사지의 농양·종기', 1560),
    ('L03.0', 'Infection around a nail (whitlow)', 'Panaris, périonyxis', '손발가락 봉와직염(생인손)', 1570),
    ('L20.9', 'Atopic eczema', 'Dermatite atopique (eczéma atopique)', '아토피 피부염', 1580),
    ('L23.9', 'Allergic contact dermatitis', 'Eczéma de contact allergique', '알레르기성 접촉피부염', 1590),
    ('L27.0', 'Drug rash', 'Éruption médicamenteuse (toxidermie)', '약물 발진', 1600),
    ('L29.9', 'Itching', 'Prurit', '가려움증', 1610),
    ('L40.9', 'Psoriasis', 'Psoriasis', '건선', 1620),
    ('L70.0', 'Acne', 'Acné', '여드름', 1630),
    ('L74.0', 'Heat rash', 'Miliaire rouge (bourbouille)', '땀띠', 1640),
    ('L91.0', 'Keloid or thick scar', 'Chéloïde, cicatrice hypertrophique', '켈로이드·비대 흉터', 1650),
    ('S01.9', 'Wound of the head or face', 'Plaie de la tête ou du visage', '머리·얼굴 열상', 1660),
    ('S06.0', 'Concussion', 'Commotion cérébrale', '뇌진탕', 1670),
    ('S09.9', 'Head injury', 'Traumatisme crânien', '머리 손상', 1680),
    ('S61.0', 'Wound of a finger', 'Plaie d''un doigt', '손가락 열상', 1690),
    ('S61.9', 'Wound of the hand or wrist', 'Plaie de la main ou du poignet', '손·손목 열상', 1700),
    ('S81.9', 'Wound of the lower leg', 'Plaie de la jambe', '아랫다리 열상', 1710),
    ('T30.1', 'First-degree burn', 'Brûlure du premier degré', '1도 화상', 1720),
    ('T30.2', 'Second-degree burn', 'Brûlure du deuxième degré', '2도 화상', 1730),
    ('T30.3', 'Third-degree burn', 'Brûlure du troisième degré', '3도 화상', 1740),
    ('T15.0', 'Foreign body in the cornea', 'Corps étranger de la cornée', '각막 이물', 1750),
    ('T16', 'Foreign body in the ear', 'Corps étranger de l''oreille', '귀 이물', 1760),
    ('T50.9', 'Medicine poisoning', 'Intoxication médicamenteuse', '약물 중독', 1770),
    ('T60.0', 'Insecticide poisoning (organophosphate)', 'Intoxication aux insecticides organophosphorés', '유기인 살충제 중독', 1780),
    ('T63.4', 'Insect sting or bite with venom', 'Piqûre d''insecte venimeux', '곤충 독(쏘임)', 1790),
    ('T78.2', 'Anaphylactic shock', 'Choc anaphylactique', '아나필락시스 쇼크', 1800),
    ('T78.4', 'Allergy', 'Allergie', '알레르기', 1810),
    ('T79.3', 'Infected wound', 'Plaie infectée', '외상 상처 감염', 1820),
    ('Z20.3', 'Exposure to rabies (animal bite)', 'Exposition à la rage (morsure d''animal)', '광견병 노출(동물에게 물림)', 1830),
    ('H00.0', 'Stye', 'Orgelet', '다래끼', 1840),
    ('H10.1', 'Allergic conjunctivitis', 'Conjonctivite allergique', '알레르기 결막염', 1850),
    ('H11.0', 'Pterygium', 'Ptérygion', '익상편', 1860),
    ('H25.9', 'Age-related cataract', 'Cataracte sénile', '노인성 백내장', 1870),
    ('H40.9', 'Glaucoma', 'Glaucome', '녹내장', 1880),
    ('H52.7', 'Refraction problem (needs glasses)', 'Trouble de la réfraction', '굴절 이상', 1890),
    ('H61.2', 'Ear wax plug', 'Bouchon de cérumen', '귀지 막힘', 1900),
    ('H66.0', 'Acute otitis media with pus', 'Otite moyenne aiguë suppurée (OMA)', '급성 화농성 중이염', 1910),
    ('H66.3', 'Chronic otitis media with pus', 'Otite moyenne chronique suppurée', '만성 화농성 중이염', 1920),
    ('H91.9', 'Hearing loss', 'Surdité, baisse de l''audition', '난청', 1930),
    ('J04.0', 'Acute laryngitis', 'Laryngite aiguë', '급성 후두염', 1940),
    ('J32.9', 'Chronic sinusitis', 'Sinusite chronique', '만성 부비동염', 1950),
    ('J35.0', 'Chronic tonsillitis', 'Amygdalite chronique', '만성 편도염', 1960),
    ('K04.0', 'Pulpitis (toothache)', 'Pulpite (rage de dent)', '치수염', 1970),
    ('K04.7', 'Dental abscess', 'Abcès dentaire', '치근단 농양', 1980),
    ('K05.0', 'Acute gingivitis', 'Gingivite aiguë', '급성 치은염', 1990),
    ('K12.0', 'Mouth ulcers (aphthae)', 'Aphtes buccaux', '구내염(아프타)', 2000),
    ('F03', 'Dementia', 'Démence', '치매', 2010),
    ('F10.2', 'Alcohol dependence', 'Dépendance à l''alcool', '알코올 의존', 2020),
    ('F20.9', 'Schizophrenia', 'Schizophrénie', '조현병', 2030),
    ('F23.9', 'Acute psychotic episode', 'Bouffée délirante aiguë (trouble psychotique aigu)', '급성 정신병적 장애', 2040),
    ('F43.2', 'Adjustment disorder', 'Trouble de l''adaptation', '적응장애', 2050),
    ('G47.0', 'Insomnia', 'Insomnie', '불면증', 2060),
    ('Z00.0', 'General medical check-up', 'Examen médical général (bilan de santé)', '일반 건강검진', 2070),
    ('Z02.1', 'Pre-employment check-up', 'Examen d''embauche', '채용 건강검진', 2080),
    ('Z02.7', 'Medical certificate requested', 'Délivrance d''un certificat médical', '진단서 발급', 2090),
    ('Z09.9', 'Follow-up visit after treatment', 'Contrôle après traitement', '치료 후 추적 진찰', 2100),
    ('Z11.1', 'Tuberculosis screening', 'Dépistage de la tuberculose', '결핵 선별검사', 2110),
    ('Z11.4', 'HIV screening', 'Dépistage du VIH', 'HIV 선별검사', 2120),
    ('Z20.1', 'Contact with tuberculosis', 'Contact avec un cas de tuberculose', '결핵 접촉', 2130),
    ('Z26.9', 'Vaccination', 'Vaccination', '예방접종', 2140),
    ('Z76.0', 'Repeat prescription', 'Renouvellement d''ordonnance', '반복 처방', 2150)
       ) AS v(code, name_en, name_fr, name_ko, n)
 WHERE NOT EXISTS (SELECT 1 FROM diagnosis_code d WHERE upper(btrim(d.code)) = upper(v.code));
