-- 204 (consultation; session number - the coordinator renumbers it): the rest of the
-- candidates - the list of frequent diagnoses goes from 315 to about 490.
--
-- When the list was widened (052) these were chosen and then left out to stay near 300, a
-- figure nobody had asked for. The director (2026-10-02): "that many more can go in as
-- well". Same rules as 052: WHO ICD-10 codes of three or four characters (edition 2010
-- and later), names in our own short wording in the three languages, not reviewed by the
-- medical staff - Settings -> Diagnostics corrects them.
-- Four candidates are NOT added because their code differs between editions or belongs
-- to a family that was left out on purpose: A90, K85.9, L89.9, O82.9
-- (wiki/reference/diagnosis-candidates.md).
--
-- A database already in use is not disturbed: a row is added only when NO row - active or
-- not - carries its code already; the rows that are there keep their names, their order
-- and their state; the new rows go after the last one. Running this twice adds nothing.
INSERT INTO diagnosis_code (code, name_en, name_fr, name_ko, sort_order)
SELECT v.code, v.name_en, v.name_fr, v.name_ko, base.last + v.n
  FROM (SELECT COALESCE(MAX(sort_order), 0) AS last FROM diagnosis_code) AS base,
       (VALUES
    ('A02.0', 'Salmonella enteritis', 'Entérite à salmonelles', '살모넬라 장염', 10),
    ('A06.4', 'Amoebic liver abscess', 'Abcès amibien du foie', '아메바 간농양', 20),
    ('A16.5', 'Tuberculous pleurisy', 'Pleurésie tuberculeuse', '결핵성 흉막염', 30),
    ('A17.0', 'Tuberculous meningitis', 'Méningite tuberculeuse', '결핵성 수막염', 40),
    ('A18.0', 'Tuberculosis of bone or joint (Pott disease)', 'Tuberculose osseuse ou articulaire (mal de Pott)', '뼈·관절 결핵', 50),
    ('A27.9', 'Leptospirosis', 'Leptospirose', '렙토스피라증', 60),
    ('A56.0', 'Chlamydial genital infection', 'Infection génitale à Chlamydia', '클라미디아 생식기 감염', 70),
    ('A59.0', 'Urogenital trichomoniasis', 'Trichomonase uro-génitale', '트리코모나스증', 80),
    ('A60.0', 'Genital herpes', 'Herpès génital', '생식기 헤르페스', 90),
    ('A63.0', 'Anogenital warts', 'Condylomes ano-génitaux', '항문생식기 사마귀(콘딜로마)', 100),
    ('A82.9', 'Rabies', 'Rage', '광견병', 110),
    ('A92.0', 'Chikungunya', 'Chikungunya', '치쿤구니야열', 120),
    ('B00.9', 'Herpes simplex infection', 'Herpès (infection à herpès simplex)', '단순포진', 130),
    ('B06.9', 'Rubella', 'Rubéole', '풍진', 140),
    ('B15.9', 'Hepatitis A', 'Hépatite A', 'A형간염', 150),
    ('B16.9', 'Acute hepatitis B', 'Hépatite B aiguë', '급성 B형간염', 160),
    ('B18.2', 'Chronic hepatitis C', 'Hépatite C chronique', '만성 C형간염', 170),
    ('B19.9', 'Viral hepatitis, type not known', 'Hépatite virale, type non précisé', '바이러스 간염(형 미상)', 180),
    ('B51.9', 'Vivax malaria', 'Paludisme à Plasmodium vivax', '삼일열 말라리아', 190),
    ('B74.9', 'Filariasis', 'Filariose', '사상충증', 200),
    ('B78.9', 'Strongyloidiasis', 'Anguillulose (strongyloïdose)', '분선충증', 210),
    ('B79', 'Whipworm infection', 'Trichocéphalose', '편충증', 220),
    ('R03.0', 'High blood pressure reading, no diagnosis of hypertension', 'Tension élevée, sans diagnostic d''HTA', '혈압 상승(고혈압 진단 없음)', 230),
    ('I25.9', 'Chronic ischaemic heart disease', 'Cardiopathie ischémique chronique', '만성 허혈성 심장병', 240),
    ('I09.9', 'Rheumatic heart disease', 'Cardiopathie rhumatismale', '류마티스성 심장병', 250),
    ('I42.0', 'Dilated cardiomyopathy', 'Cardiomyopathie dilatée', '확장성 심근병증', 260),
    ('I80.2', 'Deep vein thrombosis of the leg', 'Thrombose veineuse profonde du membre inférieur', '하지 심부정맥 혈전증', 270),
    ('I95.9', 'Low blood pressure', 'Hypotension', '저혈압', 280),
    ('J12.9', 'Viral pneumonia', 'Pneumonie virale', '바이러스 폐렴', 290),
    ('J15.9', 'Bacterial pneumonia', 'Pneumonie bactérienne', '세균성 폐렴', 300),
    ('J40', 'Bronchitis', 'Bronchite', '기관지염', 310),
    ('J42', 'Chronic bronchitis', 'Bronchite chronique', '만성 기관지염', 320),
    ('J47', 'Bronchiectasis', 'Dilatation des bronches', '기관지확장증', 330),
    ('J90', 'Pleural effusion', 'Épanchement pleural', '흉막삼출', 340),
    ('J93.9', 'Pneumothorax', 'Pneumothorax', '기흉', 350),
    ('E14.9', 'Diabetes, type not known', 'Diabète, type non précisé', '당뇨병(형 미상)', 360),
    ('E16.2', 'Hypoglycaemia', 'Hypoglycémie', '저혈당', 370),
    ('R73.9', 'High blood sugar', 'Hyperglycémie', '고혈당', 380),
    ('D53.9', 'Nutritional anaemia', 'Anémie nutritionnelle', '영양성 빈혈', 390),
    ('D57.0', 'Sickle-cell crisis', 'Crise drépanocytaire', '겸상적혈구 위기', 400),
    ('K21.0', 'Reflux with oesophagitis', 'Reflux gastro-œsophagien avec œsophagite (RGO)', '식도염을 동반한 위식도역류', 410),
    ('K26.9', 'Duodenal ulcer', 'Ulcère du duodénum', '십이지장궤양', 420),
    ('K29.5', 'Chronic gastritis', 'Gastrite chronique', '만성 위염', 430),
    ('K52.9', 'Non-infectious gastroenteritis or colitis', 'Gastro-entérite ou colite non infectieuse', '비감염성 위장염·대장염', 440),
    ('K70.3', 'Alcoholic cirrhosis', 'Cirrhose alcoolique', '알코올성 간경변', 450),
    ('K76.0', 'Fatty liver', 'Stéatose hépatique (foie gras)', '지방간', 460),
    ('N00.9', 'Acute nephritic syndrome', 'Syndrome néphritique aigu', '급성 신염 증후군', 470),
    ('N17.9', 'Acute kidney failure', 'Insuffisance rénale aiguë', '급성 신부전', 480),
    ('G20', 'Parkinson disease', 'Maladie de Parkinson', '파킨슨병', 490),
    ('G44.2', 'Tension headache', 'Céphalée de tension', '긴장성 두통', 500),
    ('G62.9', 'Polyneuropathy', 'Polyneuropathie', '다발신경병증', 510),
    ('G81.9', 'Hemiplegia', 'Hémiplégie', '편마비', 520),
    ('H81.1', 'Benign positional vertigo', 'Vertige positionnel bénin', '양성 돌발성 현기증', 530),
    ('R00.2', 'Palpitations', 'Palpitations', '두근거림', 540),
    ('R04.2', 'Coughing up blood', 'Hémoptysie', '객혈', 550),
    ('R10.3', 'Lower abdominal pain', 'Douleur du bas-ventre', '하복부 통증', 560),
    ('R12', 'Heartburn', 'Pyrosis (brûlures d''estomac)', '속쓰림', 570),
    ('R13', 'Difficulty swallowing', 'Dysphagie', '삼킴곤란', 580),
    ('R18', 'Ascites', 'Ascite', '복수', 590),
    ('R52.9', 'Pain', 'Douleur', '통증', 600),
    ('R59.0', 'Swollen lymph nodes, one area', 'Adénopathie localisée', '국소 림프절 종대', 610),
    ('R60.0', 'Local swelling (oedema)', 'Œdème localisé', '국소 부종', 620),
    ('R63.0', 'Loss of appetite', 'Anorexie (perte d''appétit)', '식욕부진', 630),
    ('E50.9', 'Vitamin A deficiency', 'Carence en vitamine A', '비타민 A 결핍', 640),
    ('K00.7', 'Teething', 'Poussée dentaire', '이가 나는 증상', 650),
    ('P07.1', 'Low birth weight', 'Faible poids de naissance', '저체중 출생아', 660),
    ('P39.1', 'Neonatal conjunctivitis', 'Conjonctivite du nouveau-né', '신생아 결막염', 670),
    ('P92.9', 'Feeding problem of the newborn', 'Difficulté d''alimentation du nouveau-né', '신생아 수유 문제', 680),
    ('Q90.9', 'Down syndrome', 'Trisomie 21', '다운증후군', 690),
    ('G80.9', 'Cerebral palsy', 'Infirmité motrice cérébrale (IMC)', '뇌성마비', 700),
    ('R62.0', 'Delayed development', 'Retard du développement', '발달 지연', 710),
    ('N61', 'Breast infection (not after childbirth)', 'Mastite ou abcès du sein (hors allaitement)', '유방염(분만과 무관)', 720),
    ('N64.4', 'Breast pain', 'Mastodynie (douleur du sein)', '유방통', 730),
    ('N60.1', 'Fibrocystic breast', 'Mastopathie fibrokystique', '섬유낭성 유방병', 740),
    ('N72', 'Cervicitis', 'Cervicite', '자궁경부염', 750),
    ('N75.0', 'Bartholin cyst', 'Kyste de la glande de Bartholin', '바르톨린샘 낭종', 760),
    ('N80.9', 'Endometriosis', 'Endométriose', '자궁내막증', 770),
    ('N81.4', 'Prolapse of the uterus', 'Prolapsus utéro-vaginal', '자궁질 탈출', 780),
    ('N87.9', 'Cervical dysplasia', 'Dysplasie du col de l''utérus', '자궁경부 이형성', 790),
    ('N97.9', 'Female infertility', 'Infertilité féminine', '여성 불임', 800),
    ('O02.1', 'Missed miscarriage', 'Grossesse arrêtée (rétention d''œuf mort)', '계류유산', 810),
    ('O06.9', 'Miscarriage or abortion, type not known', 'Avortement, type non précisé', '유산(형 미상)', 820),
    ('O15.0', 'Eclampsia in pregnancy', 'Éclampsie pendant la grossesse', '임신 중 자간증', 830),
    ('O42.9', 'Premature rupture of membranes', 'Rupture prématurée des membranes', '조기양막파수', 840),
    ('O44.1', 'Placenta praevia with bleeding', 'Placenta prævia hémorragique', '출혈을 동반한 전치태반', 850),
    ('O86.0', 'Infected caesarean or perineal wound', 'Infection de la plaie obstétricale', '산과 수술 상처 감염', 860),
    ('O91.1', 'Breast abscess while breastfeeding', 'Abcès du sein de l''allaitement', '수유기 유방 농양', 870),
    ('Z32.1', 'Pregnancy confirmed', 'Grossesse confirmée', '임신 확인', 880),
    ('Z35.9', 'Antenatal care, high-risk pregnancy', 'Consultation prénatale, grossesse à risque', '고위험 임신 산전 관리', 890),
    ('Z30.1', 'Insertion of an intrauterine device', 'Pose d''un stérilet (DIU)', '자궁내장치 삽입', 900),
    ('Z30.4', 'Follow-up of contraceptive pills or injections', 'Suivi d''une contraception (pilule, injection)', '피임약 추적 관리', 910),
    ('Z01.4', 'Routine gynaecological check', 'Examen gynécologique de routine', '부인과 정기 검진', 920),
    ('E04.1', 'Thyroid nodule', 'Nodule thyroïdien', '갑상선 결절', 930),
    ('K35.3', 'Acute appendicitis with local peritonitis', 'Appendicite aiguë avec péritonite localisée', '국소 복막염을 동반한 급성 충수염', 940),
    ('K41.9', 'Femoral hernia', 'Hernie crurale (fémorale)', '대퇴 탈장', 950),
    ('K44.9', 'Hiatus hernia', 'Hernie hiatale', '열공 탈장', 960),
    ('K62.3', 'Rectal prolapse', 'Prolapsus rectal', '직장 탈출', 970),
    ('K75.0', 'Liver abscess', 'Abcès du foie', '간농양', 980),
    ('K80.0', 'Gallstones with acute cholecystitis', 'Lithiase vésiculaire avec cholécystite aiguë', '급성 담낭염을 동반한 담석', 990),
    ('L05.0', 'Pilonidal abscess', 'Kyste pilonidal abcédé', '모소낭 농양', 1000),
    ('L04.9', 'Acute lymphadenitis', 'Adénite aiguë', '급성 림프절염', 1010),
    ('L97', 'Leg ulcer', 'Ulcère de jambe', '하지 궤양', 1020),
    ('C16.9', 'Stomach cancer', 'Cancer de l''estomac', '위암', 1030),
    ('C22.0', 'Liver cancer (hepatocellular)', 'Cancer du foie (carcinome hépatocellulaire)', '간세포암', 1040),
    ('C61', 'Prostate cancer', 'Cancer de la prostate', '전립선암', 1050),
    ('N35.9', 'Urethral stricture', 'Rétrécissement de l''urètre', '요도 협착', 1060),
    ('N41.0', 'Acute prostatitis', 'Prostatite aiguë', '급성 전립선염', 1070),
    ('N48.1', 'Balanitis', 'Balanite', '귀두포피염', 1080),
    ('I86.1', 'Varicocele', 'Varicocèle', '정계정맥류', 1090),
    ('N46', 'Male infertility', 'Infertilité masculine', '남성 불임', 1100),
    ('M00.9', 'Septic arthritis', 'Arthrite septique', '화농성 관절염', 1110),
    ('M16.9', 'Osteoarthritis of the hip', 'Arthrose de la hanche (coxarthrose)', '고관절증', 1120),
    ('M47.9', 'Spondylosis', 'Arthrose vertébrale (spondylarthrose)', '척추증', 1130),
    ('M54.4', 'Low back pain with sciatica', 'Lombosciatique', '좌골신경통을 동반한 요통', 1140),
    ('M65.3', 'Trigger finger', 'Doigt à ressaut', '방아쇠 손가락', 1150),
    ('M65.9', 'Tendon sheath inflammation', 'Ténosynovite', '건초염', 1160),
    ('M67.4', 'Ganglion cyst', 'Kyste synovial', '결절종', 1170),
    ('M72.2', 'Plantar fasciitis', 'Fasciite plantaire', '족저근막염', 1180),
    ('M75.1', 'Rotator cuff syndrome', 'Syndrome de la coiffe des rotateurs', '회전근개 증후군', 1190),
    ('M77.1', 'Tennis elbow', 'Épicondylite latérale', '외측 상과염', 1200),
    ('M79.6', 'Pain in a limb', 'Douleur d''un membre', '사지 통증', 1210),
    ('Q66.0', 'Club foot', 'Pied bot varus équin', '내반첨족(만곡족)', 1220),
    ('S02.2', 'Broken nose', 'Fracture des os du nez', '코뼈 골절', 1230),
    ('S22.3', 'Broken rib', 'Fracture de côte', '갈비뼈 골절', 1240),
    ('S42.2', 'Fracture of the upper end of the humerus', 'Fracture de l''extrémité supérieure de l''humérus', '상완골 근위부 골절', 1250),
    ('S42.3', 'Fracture of the shaft of the humerus', 'Fracture de la diaphyse de l''humérus', '상완골 몸통 골절', 1260),
    ('S62.3', 'Fracture of a metacarpal', 'Fracture d''un métacarpien', '중수골 골절', 1270),
    ('S82.0', 'Fracture of the patella', 'Fracture de la rotule', '무릎뼈 골절', 1280),
    ('S92.3', 'Fracture of a metatarsal', 'Fracture d''un métatarsien', '중족골 골절', 1290),
    ('S13.4', 'Neck sprain (whiplash)', 'Entorse cervicale', '경추 염좌', 1300),
    ('S53.1', 'Dislocated elbow', 'Luxation du coude', '팔꿈치 탈구', 1310),
    ('S63.5', 'Wrist sprain', 'Entorse du poignet', '손목 염좌', 1320),
    ('B08.1', 'Molluscum contagiosum', 'Molluscum contagiosum', '전염성 물렁종', 1330),
    ('B35.4', 'Ringworm of the body', 'Dermatophytie de la peau glabre (herpès circiné)', '체부 백선', 1340),
    ('L08.0', 'Pyoderma', 'Pyodermite', '농피증', 1350),
    ('L21.9', 'Seborrhoeic dermatitis', 'Dermite séborrhéique', '지루 피부염', 1360),
    ('L28.2', 'Prurigo', 'Prurigo', '양진', 1370),
    ('L42', 'Pityriasis rosea', 'Pityriasis rosé de Gibert', '장미색 비강진', 1380),
    ('L63.9', 'Alopecia areata', 'Pelade', '원형 탈모증', 1390),
    ('L73.2', 'Hidradenitis', 'Hidrosadénite', '화농성 한선염', 1400),
    ('L80', 'Vitiligo', 'Vitiligo', '백반증', 1410),
    ('L81.1', 'Melasma', 'Chloasma (mélasma)', '기미', 1420),
    ('L84', 'Corns and calluses', 'Cors et durillons', '티눈·굳은살', 1430),
    ('D18.0', 'Haemangioma', 'Hémangiome', '혈관종', 1440),
    ('S00.9', 'Minor head injury (bruise, graze)', 'Contusion ou plaie superficielle de la tête', '머리 표재성 손상', 1450),
    ('S01.0', 'Wound of the scalp', 'Plaie du cuir chevelu', '두피 열상', 1460),
    ('S20.2', 'Bruised chest', 'Contusion du thorax', '흉부 타박상', 1470),
    ('S51.9', 'Wound of the forearm', 'Plaie de l''avant-bras', '아래팔 열상', 1480),
    ('S80.0', 'Bruised knee', 'Contusion du genou', '무릎 타박상', 1490),
    ('S91.3', 'Wound of the foot', 'Plaie du pied', '발 열상', 1500),
    ('T17.1', 'Foreign body in the nose', 'Corps étranger du nez', '코 이물', 1510),
    ('T18.9', 'Swallowed foreign body', 'Corps étranger avalé (tube digestif)', '소화관 이물', 1520),
    ('T51.0', 'Alcohol poisoning', 'Intoxication alcoolique aiguë', '에탄올 중독', 1530),
    ('T65.9', 'Poisoning, substance not known', 'Intoxication, produit non précisé', '중독(물질 미상)', 1540),
    ('T67.0', 'Heatstroke', 'Coup de chaleur', '열사병', 1550),
    ('T78.3', 'Angioedema', 'Œdème de Quincke', '혈관부종', 1560),
    ('R40.2', 'Coma', 'Coma', '혼수', 1570),
    ('R57.9', 'Shock', 'État de choc', '쇼크', 1580),
    ('H01.0', 'Blepharitis', 'Blépharite', '눈꺼풀염', 1590),
    ('H16.9', 'Keratitis', 'Kératite', '각막염', 1600),
    ('H26.9', 'Cataract', 'Cataracte', '백내장', 1610),
    ('H52.1', 'Short sight', 'Myopie', '근시', 1620),
    ('H52.4', 'Presbyopia', 'Presbytie', '노안', 1630),
    ('H65.9', 'Otitis media with effusion', 'Otite séreuse (otite moyenne non suppurée)', '삼출성 중이염', 1640),
    ('H72.9', 'Perforated eardrum', 'Perforation du tympan', '고막 천공', 1650),
    ('H92.0', 'Earache', 'Otalgie (douleur d''oreille)', '귀 통증', 1660),
    ('J34.2', 'Deviated nasal septum', 'Déviation de la cloison nasale', '비중격 만곡', 1670),
    ('J35.3', 'Enlarged tonsils and adenoids', 'Hypertrophie des amygdales et des végétations', '편도·아데노이드 비대', 1680),
    ('J36', 'Peritonsillar abscess', 'Abcès périamygdalien (phlegmon)', '편도주위 농양', 1690),
    ('K01.1', 'Impacted tooth', 'Dent incluse', '매복치', 1700),
    ('K05.3', 'Chronic periodontitis', 'Parodontite chronique', '만성 치주염', 1710),
    ('F31.9', 'Bipolar disorder', 'Trouble bipolaire', '양극성 장애', 1720),
    ('F43.1', 'Post-traumatic stress disorder', 'État de stress post-traumatique', '외상후 스트레스 장애', 1730),
    ('Z02.0', 'Check-up for school admission', 'Examen pour admission scolaire', '입학용 건강검진', 1740),
    ('Z02.4', 'Check-up for a driving licence', 'Examen pour le permis de conduire', '운전면허용 건강검진', 1750)
       ) AS v(code, name_en, name_fr, name_ko, n)
 WHERE NOT EXISTS (SELECT 1 FROM diagnosis_code d WHERE upper(btrim(d.code)) = upper(v.code));
