-- 403 (pharmacy): the clinic's drug list from the old stock program (2026-05-15).
--
-- GENERATED by wiki/reference/drug-import-sql.js from wiki/reference/drug-import-review.csv.
-- Do not edit by hand: change the table or the script and generate again.
--
-- Decision of 2026-09-29 (wiki/handoff/coordinator.md, "가져올 약 결정"):
-- * 101 drugs go in with name, ingredient, form and category. Price 0 and no default
--   daily total or days: those are filled on site (the pharmacy and the bill show
--   "no total" / "no price" until then). Times a day and posology code come from the
--   old program's own posology where it named one clear code.
-- * Stock = the quantity of the 2026-05-15 list (total 106467); each drug gets one
--   "opening" row in the stock record with its own memo, so it is not mistaken for a
--   count adjustment. Counted again on site.
-- * 64 drugs still have something to check (quantity differing from the old note,
--   same name under two codes, form, pack unit...). They go in as they are with the list
--   in import_check; the Stock tab and the settings drug tab show it until someone marks
--   it checked (import_check_done_at / _by). The list itself is kept.
-- * 12 drugs are pack-unit drugs (025). The four whose form says tablet but whose
--   old sub-class says topical are not marked and carry a "topical" check.
-- * The 25 example drugs of 003 are hidden, not deleted. Order sets are not touched
--   (the consultation screen skips a set's line whose drug is hidden).
-- Safe to run again: existing codes are skipped, an opening row is written only for a
-- drug with no stock record, hiding touches only drugs still shown.

ALTER TABLE drug ADD COLUMN IF NOT EXISTS dosage_form VARCHAR(30);
ALTER TABLE drug ADD COLUMN IF NOT EXISTS import_check JSONB;
ALTER TABLE drug ADD COLUMN IF NOT EXISTS import_check_done_at TIMESTAMPTZ;
ALTER TABLE drug ADD COLUMN IF NOT EXISTS import_check_done_by INTEGER REFERENCES staff(id);

INSERT INTO drug (code, name, generic_name, category, dosage_form,
                  default_dose, default_freq, default_days, default_route, unit_price, stock_qty, min_stock,
                  pack_unit, pack_label, import_check)
VALUES
  ('MED-0001', 'Amlodipine 5mg', 'Amlodipine 5mg', 'Cardiovascular', 'Tablet', NULL, 1, NULL, 'QD', 0, 800, 0, FALSE, NULL, '[{"k":"review"}]'::jsonb),
  ('MED-0003', 'Memorain Cap', 'ginko leaf extract 40mg Ginseng 40% ethanol dryed extract 100mg', 'Cardiovascular', 'Capsule', NULL, 2, NULL, 'BID', 0, 90, 0, FALSE, NULL, '[{"k":"qty","d":"60캡슐*66 ≈ 3960 ≠ 90"}]'::jsonb),
  ('MED-0004', 'Chisen Cap', 'Diosmin 300mg', 'Cardiovascular', 'Capsule', NULL, 2, NULL, 'BID', 0, 3000, 0, FALSE, NULL, '[{"k":"qty","d":"60정*83 ≈ 4980 ≠ 3000"}]'::jsonb),
  ('MED-0007', 'Hutradol', 'Tylenol 162.5 + Tramadol 37.5: Hutradol tablet = Hantraset', 'Analgesic', 'Tablet', NULL, 2, NULL, 'BID', 0, 900, 0, FALSE, NULL, '[{"k":"qty","d":"850정 ≈ 850 ≠ 900"}]'::jsonb),
  ('MED-0009', 'PROFEIN', '100mg/5ml', 'Analgesic', 'Syrup', NULL, NULL, NULL, NULL, 0, 76, 0, TRUE, 'bottle', '[{"k":"qty","d":"79병 ≈ 79 ≠ 76"}]'::jsonb),
  ('MED-0010', 'SANDOL', 'Paracetamol Syrup 125/5ml', 'Analgesic', 'Syrup', NULL, NULL, NULL, NULL, 0, 26, 0, TRUE, 'bottle', '[{"k":"qty","d":"30 병 ≈ 30 ≠ 26"}]'::jsonb),
  ('MED-0011', 'Paracetamol Supp 125mg', 'Acetaminophen', 'Analgesic', 'Suppository', NULL, NULL, NULL, NULL, 0, 300, 0, FALSE, NULL, '[{"k":"form","d":"Ophthalmic → Suppository"},{"k":"qty","d":"30개 ≈ 30 ≠ 300"}]'::jsonb),
  ('MED-0012', '325mg Amiceta Tab', 'Acetaminophen Encapsulated 350mg', 'Analgesic', 'Tablet', NULL, 3, NULL, 'TID', 0, 4000, 0, FALSE, NULL, '[{"k":"form","d":"Ophthalmic → Tablet"},{"k":"name"}]'::jsonb),
  ('MED-0014', 'Taracet semi', 'Acetaminophen 162.5mg tramadol hydrocloride 18.75mg', 'Analgesic', 'Tablet', NULL, 4, NULL, 'Q6H', 0, 250, 0, FALSE, NULL, '[{"k":"form","d":"Ophthalmic → Tablet"},{"k":"qty","d":"300정*1 ≈ 300 ≠ 250"}]'::jsonb),
  ('MED-0015', 'Susphen 8hours ER 650mg', 'Acetaminophen 650mg', 'Analgesic', 'Tablet', NULL, 3, NULL, 'TID', 0, 900, 0, FALSE, NULL, '[{"k":"form","d":"Ophthalmic → Tablet"},{"k":"qty","d":"300정*1 ≈ 300 ≠ 900"}]'::jsonb),
  ('MED-0016', 'Hycephen', 'Acetaminophen 325mg ,tramadol hydrocloride 18.75mg', 'Analgesic', 'Tablet', NULL, 4, NULL, 'Q6H', 0, 390, 0, FALSE, NULL, '[{"k":"form","d":"Ophthalmic → Tablet"},{"k":"qty","d":"30정*1 ≈ 30 ≠ 390"}]'::jsonb),
  ('MED-0017', 'Susphen night Tab', 'Acetaminophen Chlorpheniramine mileate 2mg ,phenyleprine hydroclorhide 5mg', 'Respiratory', 'Tablet', NULL, NULL, NULL, NULL, 0, 600, 0, FALSE, NULL, '[{"k":"form","d":"Ophthalmic → Tablet"}]'::jsonb),
  ('MED-0019', 'IBUPROFENE SYRUP', 'IBUPROFENE SYRUP', 'Analgesic', 'Syrup', NULL, NULL, NULL, NULL, 0, 2, 0, TRUE, 'bottle', '[{"k":"review"}]'::jsonb),
  ('MED-0023', 'Perison ( /500T)', 'EPERISONE HCL 50mg: Perison tablets', 'Musculoskeletal', 'Tablet', NULL, 2, NULL, 'BID', 0, 1000, 0, FALSE, NULL, '[{"k":"qty","d":"950정 ≈ 950 ≠ 1000"},{"k":"name"}]'::jsonb),
  ('MED-0025', 'Eldolant Cap', 'Erdosteine 300mg', 'Respiratory', 'Capsule', NULL, 3, NULL, 'TID', 0, 750, 0, FALSE, NULL, '[{"k":"qty","d":"4,800캡슐 ≈ 4800 ≠ 750"}]'::jsonb),
  ('MED-0027', 'Daewoong Montelukast Tab 10mg', '(Montelukast Sodium) 10.4mg', 'Respiratory', 'Tablet', NULL, 1, NULL, 'QD', 0, 280, 0, FALSE, NULL, '[{"k":"dup","d":"MED-0028"},{"k":"qty","d":"336정 ≈ 336 ≠ 280"}]'::jsonb),
  ('MED-0028', 'Daewoong Montelukast Tab 10mg', '(Montelukast Sodium) 4mg', 'Respiratory', 'Powder / Sachet', NULL, 1, NULL, 'QD', 0, 8, 0, FALSE, NULL, '[{"k":"form","d":"Powder / Sachet"},{"k":"dup","d":"MED-0027"},{"k":"qty","d":"28포 ≈ 28 ≠ 8"}]'::jsonb),
  ('MED-0029', 'CARBO TOUX 5%', '250ML', 'Respiratory', 'Syrup', NULL, NULL, NULL, NULL, 0, 9, 0, TRUE, 'bottle', '[{"k":"qty","d":"10병 ≈ 10 ≠ 9"}]'::jsonb),
  ('MED-0031', 'Bromhexine HCL', 'Bromhexine Hydrochloride 8mg', 'Respiratory', 'Tablet', NULL, NULL, NULL, NULL, 0, 800, 0, FALSE, NULL, '[{"k":"qty","d":"1000정 ≈ 1000 ≠ 800"}]'::jsonb),
  ('MED-0034', 'Ambroxol', 'Ambroxol', 'Respiratory', 'Tablet', NULL, 3, NULL, 'TID', 0, 500, 0, FALSE, NULL, '[{"k":"review"}]'::jsonb),
  ('MED-0035', '200mg Cimetidine Tab', 'Cimetidine', 'GI', 'Tablet', NULL, 3, NULL, 'TID', 0, 750, 0, FALSE, NULL, '[{"k":"qty","d":"1,000정 ≈ 1000 ≠ 750"},{"k":"name"}]'::jsonb),
  ('MED-0037', 'Healing', '625mg', 'GI', 'Tablet', NULL, 1, NULL, 'QD', 0, 90, 0, FALSE, NULL, '[{"k":"qty","d":"500정 ≈ 500 ≠ 90"}]'::jsonb),
  ('MED-0039', 'Tirogen Tab', 'Tiropamide Hydrocholoride 100mg', 'GI', 'Tablet', NULL, 3, NULL, 'TID', 0, 750, 0, FALSE, NULL, '[{"k":"qty","d":"1,000정*1 ≈ 1000 ≠ 750"}]'::jsonb),
  ('MED-0040', 'Polybutine Tab 100mg', 'Trimebutine Maleate 100mg', 'GI', 'Tablet', NULL, 3, NULL, 'TID', 0, 750, 0, FALSE, NULL, '[{"k":"qty","d":"1,000정*1 ≈ 1000 ≠ 750"}]'::jsonb),
  ('MED-0041', '20mg Gasparmo', 'Pamotidine: 20mg', 'GI', 'Tablet', NULL, 2, NULL, 'BID', 0, 1950, 0, FALSE, NULL, '[{"k":"qty","d":"2,400정*1 ≈ 2400 ≠ 1950"},{"k":"name"}]'::jsonb),
  ('MED-0042', 'Mucoramine Tab', 'REBAMIPIDE 100mg', 'GI', 'Tablet', NULL, 2, NULL, 'BID', 0, 2250, 0, FALSE, NULL, '[{"k":"qty","d":"2,400정 ≈ 2400 ≠ 2250"}]'::jsonb),
  ('MED-0044', 'Anytal Triple Layered', 'Diastase protease Celullase 20mgTrimebutine Maleate 100mg Lipase calcium carbonate', 'GI', 'Tablet', NULL, 2, NULL, 'BID', 0, 1800, 0, FALSE, NULL, '[{"k":"qty","d":"150정*2 ≈ 300 ≠ 1800"}]'::jsonb),
  ('MED-0046', 'Mosaone', 'MOSAPRIDE Citrate Dihydrate 5,29mg', 'GI', 'Tablet', NULL, 3, NULL, 'TID', 0, 250, 0, FALSE, NULL, '[{"k":"qty","d":"500정*1 ≈ 500 ≠ 250"}]'::jsonb),
  ('MED-0047', 'Bioflor Cap/Powder', 'Saccharomyce Boulardii', 'GI', 'Capsule', NULL, NULL, NULL, NULL, 0, 390, 0, FALSE, NULL, '[{"k":"qty","d":"250정*2 ≈ 500 ≠ 390"}]'::jsonb),
  ('MED-0048', 'Medilac-S Enteric Coated Cap', 'Bacillus Subtilis 0,563 mg', 'GI', 'Capsule', NULL, NULL, NULL, NULL, 0, 1200, 0, FALSE, NULL, '[{"k":"dup","d":"MED-0079"},{"k":"qty","d":"300정*1 ≈ 300 ≠ 1200"}]'::jsonb),
  ('MED-0049', 'Nexierd', 'Esomeprazole Magnesium Dihydrate', 'GI', 'Tablet', NULL, 1, NULL, 'QD', 0, 420, 0, FALSE, NULL, '[{"k":"qty","d":"1정*1 ≈ 1 ≠ 420"}]'::jsonb),
  ('MED-0054', 'Almagel', 'Almagate 500mg', 'GI', 'Tablet', NULL, 3, NULL, 'TID', 0, 1000, 0, FALSE, NULL, '[{"k":"form","d":"Vaginal / Gel → Tablet"}]'::jsonb),
  ('MED-0056', 'Beposen', 'BEPOTASTINE BESILATE 10mg', 'Antihistamine', 'Tablet', NULL, 2, NULL, 'BID', 0, 1380, 0, FALSE, NULL, '[{"k":"qty","d":"600정 ≈ 600 ≠ 1380"}]'::jsonb),
  ('MED-0057', 'Beari On', 'BEPOTASTINE BESILATE 10mg', 'Antihistamine', 'Tablet', NULL, 2, NULL, 'BID', 0, 600, 0, FALSE, NULL, '[{"k":"qty","d":"1,500정 ≈ 1500 ≠ 600"}]'::jsonb),
  ('MED-0058', 'Twolion', 'BEPOTASTINE BESILATE 10mg', 'Antihistamine', 'Tablet', NULL, 2, NULL, 'BID', 0, 1350, 0, FALSE, NULL, '[{"k":"qty","d":"300정*1 ≈ 300 ≠ 1350"}]'::jsonb),
  ('MED-0061', 'Bonaling-A Tab', 'Dimenhydrinate 50mg', 'Antihistamine', 'Tablet', NULL, 2, NULL, 'BID', 0, 500, 0, FALSE, NULL, '[{"k":"dup","d":"MED-0062"},{"k":"qty","d":"1,000정 ≈ 1000 ≠ 500"}]'::jsonb),
  ('MED-0062', 'Bonaling-A Tab', 'Dimenhydrinate 51mg', 'Antihistamine', 'Tablet', NULL, 2, NULL, 'BID', 0, 500, 0, FALSE, NULL, '[{"k":"dup","d":"MED-0061"},{"k":"qty","d":"1,001정 ≈ 1001 ≠ 500"}]'::jsonb),
  ('MED-0063', 'Peniramin Tab 2mg', '(Chlorpheniramine Maleate) 2mg', 'Antihistamine', 'Tablet', NULL, 1, NULL, 'QD', 0, 1000, 0, FALSE, NULL, '[{"k":"qty","d":"1,700정 ≈ 1700 ≠ 1000"}]'::jsonb),
  ('MED-0065', 'Prednisolone 5mg Tab', 'Prednisolone 5mg', 'Corticosteroid', 'Tablet', NULL, NULL, NULL, NULL, 0, 4500, 0, FALSE, NULL, '[{"k":"qty","d":"4900 ≈ 4900 ≠ 4500"}]'::jsonb),
  ('MED-0066', 'Metronidazole vaginal gel 5g', '(Metronidazole)', 'Gynecology', 'Vaginal / Gel', NULL, 2, NULL, 'BID', 0, 98, 0, TRUE, 'tube', '[{"k":"qty","d":"100개 ≈ 100 ≠ 98"},{"k":"posology","d":"1_2T BID"}]'::jsonb),
  ('MED-0068', 'Amoxicillin 500mg', 'Amoxicillin 500mg', 'Antibiotic', 'Capsule', NULL, 2, NULL, 'BID', 0, 2000, 0, FALSE, NULL, '[{"k":"dup","d":"MED-0069"},{"k":"qty","d":"650캡슐 ≈ 650 ≠ 2000"},{"k":"review"},{"k":"posology","d":"1_2T BID"}]'::jsonb),
  ('MED-0069', 'Amoxicillin 500mg', 'Amoxicillin 500mg', 'Antibiotic', 'Capsule', NULL, 2, NULL, 'BID', 0, 2500, 0, FALSE, NULL, '[{"k":"dup","d":"MED-0068"},{"k":"qty","d":"1,000캡슐 ≈ 1000 ≠ 2500"},{"k":"review"},{"k":"posology","d":"1_2T BID"}]'::jsonb),
  ('MED-0071', 'Flasinyl Tab', 'Metronidazole', 'Antibiotic', 'Tablet', NULL, 3, NULL, 'TID', 0, 800, 0, FALSE, NULL, '[{"k":"qty","d":"1,000정 ≈ 1000 ≠ 800"}]'::jsonb),
  ('MED-0073', 'Albendazole 400mg', 'Albendazole 400mg', 'Antiparasitic', 'Tablet', NULL, NULL, NULL, NULL, 0, 550, 0, FALSE, NULL, '[{"k":"qty","d":"990정 ≈ 990 ≠ 550"},{"k":"review"}]'::jsonb),
  ('MED-0076', 'Zelcome', 'Flubendazole 500mg', 'Antiparasitic', 'Tablet', NULL, 1, NULL, 'QD', 0, 32, 0, FALSE, NULL, '[{"k":"qty","d":"2정*8 ≈ 16 ≠ 32"}]'::jsonb),
  ('MED-0077', 'Combimal', 'Sulfadoxine', 'Antimalarial', 'Tablet', NULL, 1, NULL, 'QD', 0, 300, 0, FALSE, NULL, '[{"k":"malaria"}]'::jsonb),
  ('MED-0078', 'M-Artefix 80mg/480mg', 'M_Artefix 80mg/480mg', 'Antimalarial', 'Tablet', NULL, NULL, NULL, NULL, 0, 30, 0, FALSE, NULL, '[{"k":"malaria"}]'::jsonb),
  ('MED-0079', 'Medilac-S Enteric Coated Cap', 'Bacillus Subtilis-Enterococcus Faecium Culture 125mg', 'GI', 'Capsule', NULL, NULL, NULL, NULL, 0, 9000, 0, FALSE, NULL, '[{"k":"dup","d":"MED-0048"}]'::jsonb),
  ('MED-0080', 'Silcon Tab', 'Polycarbophil Calcium 625mg', 'GI', 'Tablet', NULL, NULL, NULL, NULL, 0, 500, 0, FALSE, NULL, '[{"k":"form","d":"Ophthalmic → Tablet"},{"k":"dup","d":"MED-0081"}]'::jsonb),
  ('MED-0081', 'Silcon Tab', 'Polycarbophil Calcium 625mg', 'GI', 'Tablet', NULL, NULL, NULL, NULL, 0, 100, 0, FALSE, NULL, '[{"k":"form","d":"Ophthalmic → Tablet"},{"k":"dup","d":"MED-0080"}]'::jsonb),
  ('MED-0082', 'Magmil Tab', 'Magnesium hydroxide', 'GI', 'Tablet', NULL, NULL, NULL, NULL, 0, 500, 0, FALSE, NULL, '[{"k":"qty","d":"900정 ≈ 900 ≠ 500"}]'::jsonb),
  ('MED-0083', 'Neutech Tab', 'Aloe 2mg caffeine hydrate 20mg Chlorpheniramine mileate 2mg Ethyl ampinobenzoate30mg Nicotinamide20mg Papaverine hydrochloryde Riboflavin Thiamine Hydrochoride 10mg', 'Cardiovascular', 'Tablet', NULL, NULL, NULL, NULL, 0, 2000, 0, FALSE, NULL, '[{"k":"qty","d":"90정*54 ≈ 4860 ≠ 2000"}]'::jsonb),
  ('MED-0084', 'Pansidil Cap', 'Calcium Pantothenate 60mg Keratine L Cystine 20mg medicinal yeast 100mg P Aminobenzoic Acid 20mg Thiamine Nitrate 60mg', 'Dermatology', 'Capsule', NULL, 3, NULL, 'TID', 0, 7290, 0, FALSE, NULL, '[{"k":"qty","d":"180정*20 ≈ 3600 ≠ 1890"},{"k":"qty","d":"180정*20 ≈ 3600 ≠ 1800"}]'::jsonb),
  ('MED-0086', 'Feramine Q Tab', 'Cimicifuga Rhizome Extract 0,0364 Ml Saint john ''S Wort 80% MEthanol dried extract', 'Gynecology', 'Tablet', NULL, 2, NULL, 'BID', 0, 4260, 0, FALSE, NULL, '[{"k":"qty","d":"180정*17 ≈ 3060 ≠ 1200"},{"k":"posology","d":"1_2T BID"}]'::jsonb),
  ('MED-0087', 'Caritopotene Soft Cap', 'Cucurbit Semen Oil Ext', 'Urology', 'Capsule', NULL, 2, NULL, 'BID', 0, 2860, 0, FALSE, NULL, '[{"k":"qty","d":"60정*44 ≈ 2640 ≠ 2460"},{"k":"qty","d":"60정*44 ≈ 2640 ≠ 400"}]'::jsonb),
  ('MED-0088', 'Insandol Tab', 'Titrated Ext of the Unsaponifiable Fraction Of the Zea mays L 35mg', 'Other', 'Tablet', NULL, 3, NULL, 'TID', 0, 6000, 0, FALSE, NULL, '[{"k":"posology","d":"1_2T TID"}]'::jsonb),
  ('MED-0090', 'Beecom tab', 'Ascorbic Acid Calcium Pantothenate 61mg Cyanocobalami D biotin', 'Vitamin', 'Tablet', NULL, NULL, NULL, NULL, 0, 0, 0, FALSE, NULL, '[{"k":"zero"}]'::jsonb),
  ('MED-0091', 'Hemorex 35mg', 'Pramoxine Hydrochloride 10mg', 'Dermatology', 'Tablet', NULL, NULL, NULL, NULL, 0, 18, 0, FALSE, NULL, '[{"k":"topical"}]'::jsonb),
  ('MED-0093', 'Madecassol', 'Titrated Ext of Centella', 'Dermatology', 'Tablet', NULL, NULL, NULL, NULL, 0, 209, 0, FALSE, NULL, '[{"k":"dup","d":"MED-0094, MED-0095"},{"k":"topical"}]'::jsonb),
  ('MED-0094', 'Madecassol', 'Titrated Ext of Centella', 'Dermatology', 'Tablet', NULL, NULL, NULL, NULL, 0, 93, 0, FALSE, NULL, '[{"k":"dup","d":"MED-0093, MED-0095"},{"k":"topical"}]'::jsonb),
  ('MED-0095', 'Madecassol', 'Neomycin Sulfate Titrated Ext of Centella', 'Dermatology', 'Tablet', NULL, NULL, NULL, NULL, 0, 108, 0, FALSE, NULL, '[{"k":"dup","d":"MED-0093, MED-0094"},{"k":"topical"}]'::jsonb),
  ('MED-0096', 'Vaseline blanche', 'Vaseline blanche', 'Dermatology', 'Topical', NULL, NULL, NULL, NULL, 0, 1, 0, TRUE, 'unit', '[{"k":"qty","d":"31개 ≈ 31 ≠ 1"},{"k":"review"},{"k":"packlabel","d":"31개"}]'::jsonb),
  ('MED-0097', 'Sulfadiazine', 'Sulfadiazine', 'Dermatology', 'Topical', NULL, NULL, NULL, NULL, 0, 1, 0, TRUE, 'unit', '[{"k":"qty","d":"20개 ≈ 20 ≠ 1"},{"k":"review"},{"k":"packlabel","d":"20개"}]'::jsonb),
  ('MED-0098', 'Neodex ophthalmic ointment 5g', 'Oxytetracycline Hydrochloride 5mg/g Polymyxin B Sulfate', 'Ophthalmic', 'Ophthalmic', NULL, NULL, NULL, NULL, 0, 3, 0, TRUE, 'tube', '[{"k":"qty","d":"8개 ≈ 8 ≠ 3"}]'::jsonb),
  ('MED-0002', 'Guinep', 'ginko leaf extract 40mg', 'Cardiovascular', 'Tablet', NULL, NULL, NULL, NULL, 0, 120, 0, FALSE, NULL, NULL),
  ('MED-0005', 'Retium', 'Dobesilate calcium hydrate 250mg', 'Cardiovascular', 'Tablet', NULL, 2, NULL, 'BID', 0, 180, 0, FALSE, NULL, NULL),
  ('MED-0006', 'Januvia 50mg', 'SILTAGLIPINE HCL HYDRATE 56.69mg', 'Endocrine', 'Tablet', NULL, 1, NULL, 'QD', 0, 2016, 0, FALSE, NULL, NULL),
  ('MED-0008', 'Peloen', 'PELUBIPROFEN30mg:Peloen tablets', 'Analgesic', 'Tablet', NULL, NULL, NULL, NULL, 0, 1800, 0, FALSE, NULL, NULL),
  ('MED-0013', 'Ceclo Tab', 'Aceclofenac 100mg', 'Analgesic', 'Tablet', NULL, 3, NULL, 'TID', 0, 1000, 0, FALSE, NULL, NULL),
  ('MED-0018', 'Loxfenin', 'Loxoprofen Sodium Hydrate 68.1mg', 'Analgesic', 'Tablet', NULL, NULL, NULL, NULL, 0, 30, 0, FALSE, NULL, NULL),
  ('MED-0020', 'Laxib Tab', 'Celecoxib ( NSAID)', 'Analgesic', 'Tablet', NULL, NULL, NULL, NULL, 0, 120, 0, FALSE, NULL, NULL),
  ('MED-0021', 'Tak -Sen Soft Cap', 'Naproxen( NSAID )100mg', 'Analgesic', 'Capsule', NULL, NULL, NULL, NULL, 0, 100, 0, FALSE, NULL, NULL),
  ('MED-0022', 'Aceclofen', 'Aceclofenac 100mg', 'Analgesic', 'Tablet', NULL, 2, NULL, 'BID', 0, 900, 0, FALSE, NULL, NULL),
  ('MED-0024', 'Miaron', 'Afloqualon 20 mg', 'Musculoskeletal', 'Tablet', NULL, 3, NULL, 'TID', 0, 1000, 0, FALSE, NULL, NULL),
  ('MED-0026', 'Sudafed Tab', 'Peseudoephedrine Hydrocholoride 60mg', 'Respiratory', 'Tablet', NULL, NULL, NULL, NULL, 0, 2000, 0, FALSE, NULL, NULL),
  ('MED-0030', 'ephedrine 40mg 4%', 'Montelukast Sodium', 'Respiratory', 'Tablet', NULL, NULL, NULL, NULL, 0, 500, 0, FALSE, NULL, NULL),
  ('MED-0032', 'Levopect', 'Levodroprizine 45 mg', 'Respiratory', 'Tablet', NULL, 2, NULL, 'BID', 0, 300, 0, FALSE, NULL, NULL),
  ('MED-0033', 'Muco -One', 'Erdosteine 300mg', 'Respiratory', 'Tablet', NULL, NULL, NULL, NULL, 0, 1000, 0, FALSE, NULL, NULL),
  ('MED-0036', 'Macperan Tab', 'Metoclopramide 3.84mg', 'GI', 'Tablet', NULL, NULL, NULL, NULL, 0, 1000, 0, FALSE, NULL, NULL),
  ('MED-0038', 'Amis Tab', 'Artemisia Herb 95% Ethanol Soft Ext(20->1)', 'GI', 'Tablet', NULL, 2, NULL, 'BID', 0, 3000, 0, FALSE, NULL, NULL),
  ('MED-0043', 'Bamedin', 'REBAMIPIDE 100mg', 'GI', 'Tablet', NULL, 2, NULL, 'BID', 0, 900, 0, FALSE, NULL, NULL),
  ('MED-0045', 'Humorid', 'MOSAPRIDE SODIUM 5mg', 'GI', 'Tablet', NULL, 3, NULL, 'TID', 0, 1800, 0, FALSE, NULL, NULL),
  ('MED-0050', 'Bigcidine Cap', 'Nizatidine 150 mg (H2 Antagonist)', 'GI', 'Capsule', NULL, NULL, NULL, NULL, 0, 420, 0, FALSE, NULL, NULL),
  ('MED-0051', 'Gaster', 'Famotidine 20mg(H2 Antagonist)', 'GI', 'Tablet', NULL, NULL, NULL, NULL, 0, 1800, 0, FALSE, NULL, NULL),
  ('MED-0052', 'Stillen 2X', 'Artemisia Herb 95% Ethanol Soft Ext(20->1)', 'GI', 'Tablet', NULL, 2, NULL, 'BID', 0, 400, 0, FALSE, NULL, NULL),
  ('MED-0053', 'Algicell', 'Sodium Alginate', 'GI', 'Tablet', NULL, NULL, NULL, NULL, 0, 360, 0, FALSE, NULL, NULL),
  ('MED-0055', 'Anemo', 'Scopolia Extract powder 10% Calcium carbonate', 'GI', 'Powder / Sachet', NULL, 3, NULL, 'TID', 0, 2000, 0, FALSE, NULL, NULL),
  ('MED-0059', 'Potas', 'BEPOTASTINE BESILATE 10mg', 'Antihistamine', 'Tablet', NULL, 2, NULL, 'BID', 0, 300, 0, FALSE, NULL, NULL),
  ('MED-0060', 'Arazine', 'BEPOTASTINE BESILATE 10mg', 'Antihistamine', 'Tablet', NULL, 2, NULL, 'BID', 0, 60, 0, FALSE, NULL, NULL),
  ('MED-0064', 'Dexamethasone Tab', 'Dexamethasone 0.75mg', 'Corticosteroid', 'Tablet', NULL, NULL, NULL, NULL, 0, 1000, 0, FALSE, NULL, NULL),
  ('MED-0067', 'Clotrimazole vaginal tablet 100mg', 'Clotrimazole', 'Gynecology', 'Tablet', NULL, NULL, NULL, NULL, 0, 48, 0, FALSE, NULL, NULL),
  ('MED-0070', 'Cefaclor', 'Cefaclor Hydrate 250 mg (Cephalosporine )', 'Antibiotic', 'Capsule', NULL, 3, NULL, 'TID', 0, 300, 0, FALSE, NULL, NULL),
  ('MED-0072', 'Rosyth', 'ROXITHROMYCIN 150mg', 'Antibiotic', 'Tablet', NULL, NULL, NULL, NULL, 0, 700, 0, FALSE, NULL, NULL),
  ('MED-0074', 'Gentazole 2tab -set', 'Albendazole 400mg', 'Antiparasitic', 'Tablet', NULL, 1, NULL, 'QD', 0, 230, 0, FALSE, NULL, NULL),
  ('MED-0075', 'Alnazole 2tab -set', 'Albendazole 400mg', 'Antiparasitic', 'Tablet', NULL, 1, NULL, 'QD', 0, 334, 0, FALSE, NULL, NULL),
  ('MED-0085', 'Ginsenside Cap', 'Ginseng40% Ethanol dried extract', 'Vitamin', 'Capsule', NULL, NULL, NULL, NULL, 0, 3240, 0, FALSE, NULL, NULL),
  ('MED-0089', 'Tasna Vita Tab', 'Ascorbic Acid Calcium Pantothenate 60mg Cyanocobalami D biotin', 'Vitamin', 'Tablet', NULL, 1, NULL, 'QD', 0, 2000, 0, FALSE, NULL, NULL),
  ('MED-0092', 'Hydrocortisone Cream 20mg', '(Hydrocortisone)', 'Dermatology', 'Topical', NULL, NULL, NULL, NULL, 0, 88, 0, TRUE, 'tube', NULL),
  ('MED-0099', 'Tolon Eye Drops', 'Fluromethanole 1mg/L', 'Ophthalmic', 'Ophthalmic', NULL, NULL, NULL, NULL, 0, 33, 0, TRUE, 'bottle', NULL),
  ('MED-0100', 'Tolon T Eye Drops', 'Fluromethanole 1mg/Ltetrahydrozoline Hydrocloride 0,25mg/L', 'Ophthalmic', 'Ophthalmic', NULL, NULL, NULL, NULL, 0, 12, 0, TRUE, 'bottle', NULL),
  ('MED-0101', 'Cuolone Eye Drops', 'Sodium Hyaluronate 1mg/L', 'Ophthalmic', 'Ophthalmic', NULL, NULL, NULL, NULL, 0, 12, 0, TRUE, 'bottle', NULL)
ON CONFLICT (code) DO NOTHING;

INSERT INTO stock_movement (drug_id, kind, qty, stock_before, stock_after, memo)
SELECT d.id, 'opening', GREATEST(COALESCE(d.stock_qty, 0), 0), 0, GREATEST(COALESCE(d.stock_qty, 0), 0),
       'Imported from the old stock program (count of 2026-05-15)'
  FROM drug d
 WHERE d.code IN (
  'MED-0001', 'MED-0003', 'MED-0004', 'MED-0007', 'MED-0009', 'MED-0010', 'MED-0011', 'MED-0012',
  'MED-0014', 'MED-0015', 'MED-0016', 'MED-0017', 'MED-0019', 'MED-0023', 'MED-0025', 'MED-0027',
  'MED-0028', 'MED-0029', 'MED-0031', 'MED-0034', 'MED-0035', 'MED-0037', 'MED-0039', 'MED-0040',
  'MED-0041', 'MED-0042', 'MED-0044', 'MED-0046', 'MED-0047', 'MED-0048', 'MED-0049', 'MED-0054',
  'MED-0056', 'MED-0057', 'MED-0058', 'MED-0061', 'MED-0062', 'MED-0063', 'MED-0065', 'MED-0066',
  'MED-0068', 'MED-0069', 'MED-0071', 'MED-0073', 'MED-0076', 'MED-0077', 'MED-0078', 'MED-0079',
  'MED-0080', 'MED-0081', 'MED-0082', 'MED-0083', 'MED-0084', 'MED-0086', 'MED-0087', 'MED-0088',
  'MED-0090', 'MED-0091', 'MED-0093', 'MED-0094', 'MED-0095', 'MED-0096', 'MED-0097', 'MED-0098',
  'MED-0002', 'MED-0005', 'MED-0006', 'MED-0008', 'MED-0013', 'MED-0018', 'MED-0020', 'MED-0021',
  'MED-0022', 'MED-0024', 'MED-0026', 'MED-0030', 'MED-0032', 'MED-0033', 'MED-0036', 'MED-0038',
  'MED-0043', 'MED-0045', 'MED-0050', 'MED-0051', 'MED-0052', 'MED-0053', 'MED-0055', 'MED-0059',
  'MED-0060', 'MED-0064', 'MED-0067', 'MED-0070', 'MED-0072', 'MED-0074', 'MED-0075', 'MED-0085',
  'MED-0089', 'MED-0092', 'MED-0099', 'MED-0100', 'MED-0101')
   AND NOT EXISTS (SELECT 1 FROM stock_movement m WHERE m.drug_id = d.id);

UPDATE drug SET is_active = FALSE, updated_at = NOW()
 WHERE is_active AND code IN (
  'PCM500', 'PCM250', 'BRUFEN', 'BRUFEN4', 'DICLO', 'AMOX500', 'AMOX250', 'CEFT',
  'METRO', 'ACT01', 'AMLO5', 'AMLO10', 'METF500', 'METF850', 'OMEP20', 'RECOMID',
  'PRED5', 'CHLOR', 'LORAT', 'SALB', 'ORS', 'ZINC', 'IRON', 'FOLIC',
  'CODAEP');
